import Link from "next/link";
import { ArrowRight, BookOpen, Check, Clock3, HeartHandshake, ShieldCheck, UsersRound } from "lucide-react";
import { pageWrap, primaryLink, outlineLink, PageIntro } from "./Shared";

const pillars = [
  ["One-to-one learning", "Lessons leave room for questions, correction, and a pace that respects the learner.", UsersRound],
  ["Qualified teachers", "The academy will connect learners with educators whose profiles and availability are verified.", ShieldCheck],
  ["Flexible scheduling", "A consistent learning rhythm should fit around real families, time zones, and responsibilities.", Clock3],
  ["Personalized learning", "Plans can grow with the student instead of asking every learner to follow the same path.", HeartHandshake],
];

export function AboutPage() {
  return <main>
    <section className="geometric-pattern border-b border-[#e7e5df] bg-[#f5f1e8] py-20 sm:py-24"><div className={pageWrap}><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#147d70]">About Noor Academy</p><h1 className="mt-4 max-w-4xl font-display text-5xl leading-[0.95] text-[#17324d] sm:text-7xl">A calmer, more personal way to learn the Quran.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#667085]">Noor Academy is being shaped as an international online learning space where students and families can build a meaningful, sustainable relationship with Quran learning.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/trial" className={primaryLink}>Book a Free Trial <ArrowRight size={17} aria-hidden="true" /></Link><Link href="/courses" className={outlineLink}>Explore Courses</Link></div></div></section>
    <section className="bg-white py-24"><div className={`${pageWrap} grid min-w-0 gap-14 lg:grid-cols-[0.85fr_1.15fr]`}><div className="min-w-0"><PageIntro eyebrow="Our mission" title="Make good learning habits feel possible." description="The Noor Academy experience is designed around clarity, consistency, and human connection. The interface is API-ready so the future platform can keep the experience as thoughtful as the teaching." /></div><div className="min-w-0 break-words rounded-2xl border border-[#e7e5df] bg-[#fcfbf7] p-7 sm:p-10"><BookOpen size={31} className="text-[#147d70]" aria-hidden="true" /><p className="mt-8 break-words font-display text-3xl leading-tight text-[#17324d]">Learn the Quran. Nourish Your Soul.</p><p className="mt-5 break-words text-base leading-8 text-[#667085]">Our philosophy begins with a simple belief: learning is more lasting when it is welcoming, focused, and shaped around the person in front of the teacher.</p></div></div></section>
    <section className="bg-[#fcfbf7] py-24"><div className={pageWrap}><PageIntro eyebrow="What makes the experience different" title="Structure with warmth, progress with purpose." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{pillars.map(([title, text, Icon]) => { const PillarIcon = Icon as typeof UsersRound; return <article key={title as string} className="rounded-2xl border border-[#e7e5df] bg-white p-6"><span className="flex size-11 items-center justify-center rounded-xl bg-[#eef7f3] text-[#147d70]"><PillarIcon size={21} aria-hidden="true" /></span><h2 className="mt-6 font-display text-2xl text-[#17324d]">{title as string}</h2><p className="mt-3 text-sm leading-6 text-[#667085]">{text as string}</p></article>; })}</div></div></section>
    <section className="bg-[#17324d] py-24 text-white"><div className={`${pageWrap} grid min-w-0 gap-12 lg:grid-cols-[0.8fr_1.2fr]`}><div className="min-w-0"><PageIntro dark eyebrow="Learning philosophy" title="Small steps can become a lifelong rhythm." description="From the first letter to deeper study, learners need clear next steps, patient feedback, and space to return to what matters." /></div><div className="grid min-w-0 gap-4 sm:grid-cols-2">{["Start with the learner", "Practice with intention", "Reflect on progress", "Keep the door open"].map((item) => <div key={item} className="flex min-w-0 items-start gap-3 rounded-xl border border-white/10 bg-white/[0.06] p-5"><Check size={18} className="mt-0.5 shrink-0 text-[#c6a15b]" aria-hidden="true" /><span className="min-w-0 break-words text-sm font-bold text-white/85">{item}</span></div>)}</div></div></section>
    <section className="bg-[#eef7f3] py-24"><div className={pageWrap}><PageIntro eyebrow="The journey" title="A clear path from first conversation to steady progress." /><div className="mt-12 grid gap-8 md:grid-cols-4">{[["01", "Book a free trial"], ["02", "Meet your teacher"], ["03", "Follow your plan"], ["04", "Track your progress"]].map(([number, title], index) => <div key={number} className="relative text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-full border border-[#c6a15b] bg-white font-display text-2xl text-[#17324d]">{number}</div>{index < 3 && <span className="absolute left-[calc(50%+42px)] right-[calc(-50%+42px)] top-7 hidden h-px bg-[#d9cda9] md:block" aria-hidden="true" />}<h2 className="mt-5 font-display text-xl text-[#17324d]">{title}</h2></div>)}</div></div></section>
    <section className="bg-[#147d70] py-20"><div className={`${pageWrap} flex min-w-0 flex-col items-start justify-between gap-6 sm:flex-row sm:items-center`}><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#e9ddbf]">Your learning journey</p><h2 className="mt-2 break-words font-display text-4xl text-white">Ready to begin?</h2><p className="mt-3 break-words text-sm text-white/75">Start with a free trial or explore the courses available in the demo catalog.</p></div><div className="flex w-full min-w-0 flex-col gap-3 sm:w-auto sm:flex-row"><Link href="/trial" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-[#17324d]">Book a Free Trial <ArrowRight size={16} aria-hidden="true" /></Link><Link href="/courses" className="inline-flex min-h-11 items-center justify-center rounded-full border border-white/30 px-5 text-sm font-bold text-white hover:bg-white/10">Explore Courses</Link></div></div></section>
  </main>;
}
