import Link from "next/link";
import { ArrowRight, Check, Clock3, UsersRound } from "lucide-react";
import type { CourseRecord } from "@/data/publicPages";
import { innerFaqs } from "@/data/publicPages";
import { Accordion, outlineLink, pageWrap, primaryLink, PageIntro } from "./Shared";

export function CourseDetailPage({ course }: { course: CourseRecord }) {
  const Icon = course.icon;
  return <main>
    <section className="bg-[#f5f1e8] py-16 sm:py-20"><div className={`${pageWrap} grid items-center gap-10 lg:grid-cols-[1.1fr_0.9fr]`}><div><Link href="/courses" className="text-sm font-bold text-[#147d70]">Courses / {course.title}</Link><p className="mt-8 text-xs font-bold uppercase tracking-[0.18em] text-[#c6a15b]">Demo course detail</p><h1 className="mt-4 font-display text-5xl leading-[0.95] text-[#17324d] sm:text-7xl">{course.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#667085]">{course.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/trial" className={primaryLink}>Book Free Trial <ArrowRight size={17} aria-hidden="true" /></Link><Link href="/courses" className={outlineLink}>Back to Courses</Link></div></div><div className="rounded-[2rem] border border-[#e7e5df] bg-white p-6 shadow-[0_16px_40px_rgba(23,50,77,0.06)]"><div className="flex h-48 items-center justify-center rounded-2xl" style={{ backgroundColor: course.tint }}><Icon size={78} strokeWidth={1.2} className="text-[#147d70]" aria-hidden="true" /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#98a2b3]">Level</p><p className="mt-1 text-sm font-bold text-[#17324d]">{course.level}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#98a2b3]">Age group</p><p className="mt-1 text-sm font-bold text-[#17324d]">{course.ageGroup}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#98a2b3]">Class type</p><p className="mt-1 text-sm font-bold text-[#17324d]">{course.classType}</p></div></div></div></div></section>
    <section className="bg-white py-20"><div className={`${pageWrap} grid gap-14 lg:grid-cols-[1.1fr_0.9fr]`}><div><PageIntro eyebrow="Course overview" title="A clear path with room for your pace." description={course.audience} /><div className="mt-10"><h2 className="font-display text-3xl text-[#17324d]">Learning objectives</h2><ul className="mt-6 grid gap-3 sm:grid-cols-2">{course.objectives.map((objective) => <li key={objective} className="flex gap-3 rounded-xl bg-[#eef7f3] p-4 text-sm leading-6 text-[#667085]"><Check size={18} className="mt-1 shrink-0 text-[#147d70]" aria-hidden="true" />{objective}</li>)}</ul></div></div><div className="rounded-2xl border border-[#e7e5df] bg-[#fcfbf7] p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#c6a15b]">What students will learn</p><ul className="mt-6 space-y-4">{course.outcomes.map((outcome) => <li key={outcome} className="flex gap-3 text-sm leading-6 text-[#667085]"><Check size={18} className="mt-1 shrink-0 text-[#147d70]" aria-hidden="true" />{outcome}</li>)}</ul><div className="mt-8 border-t border-[#e7e5df] pt-6"><div className="flex items-center gap-3 text-sm font-bold text-[#17324d]"><Clock3 size={18} className="text-[#147d70]" aria-hidden="true" /> Flexible lesson rhythm</div><div className="mt-3 flex items-center gap-3 text-sm font-bold text-[#17324d]"><UsersRound size={18} className="text-[#147d70]" aria-hidden="true" /> One-to-one guidance</div></div></div></div></section>
    <section className="bg-[#fcfbf7] py-20"><div className={pageWrap}><PageIntro eyebrow="Curriculum" title="A modular learning experience." /><div className="mt-10 grid gap-4 md:grid-cols-2">{course.modules.map((module, index) => <article key={module} className="flex gap-5 rounded-2xl border border-[#e7e5df] bg-white p-6"><span className="font-display text-3xl text-[#c6a15b]">0{index + 1}</span><div><h2 className="font-display text-2xl text-[#17324d]">{module}</h2><p className="mt-2 text-sm leading-6 text-[#667085]">Demo module detail to be supplied by the connected course service.</p></div></article>)}</div></div></section>
    <section className="bg-white py-20"><div className={`${pageWrap} grid gap-12 lg:grid-cols-[0.8fr_1.2fr]`}><PageIntro eyebrow="Questions about this course" title="A few helpful answers." /><Accordion items={innerFaqs} /></div></section>
    <section className="bg-[#147d70] py-20"><div className={`${pageWrap} flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center`}><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#e9ddbf]">Ready when you are</p><h2 className="mt-2 font-display text-4xl text-white">Try {course.title} with a free lesson.</h2><p className="mt-3 text-sm text-white/75">Course availability and trial confirmation will come from the academy service.</p></div><Link href="/trial" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-[#17324d]">Book Free Trial <ArrowRight size={16} aria-hidden="true" /></Link></div></section>
  </main>;
}
