import Link from "next/link";
import { ArrowRight, Check, Clock3, Globe2, MessageCircle, ShieldCheck } from "lucide-react";
import type { TeacherRecord } from "@/data/publicPages";
import { teacherFaqs } from "@/data/publicPages";
import { Accordion, outlineLink, pageWrap, primaryLink, PageIntro } from "./Shared";

export function TeacherDetailPage({ teacher }: { teacher: TeacherRecord }) {
  return <main>
    <section className="bg-[#f5f1e8] py-16 sm:py-20"><div className={`${pageWrap} grid items-center gap-10 lg:grid-cols-[0.75fr_1.25fr]`}><div className="flex h-80 items-end justify-center rounded-[2rem] border border-[#e7e5df] bg-[#eaf4ef] p-8 sm:h-96"><div className="flex size-40 items-center justify-center rounded-full border-8 border-white bg-[#147d70] font-display text-5xl text-white shadow-xl">{teacher.initials}</div></div><div><Link href="/teachers" className="text-sm font-bold text-[#147d70]">Teachers / {teacher.name}</Link><p className="mt-8 text-xs font-bold uppercase tracking-[0.18em] text-[#c6a15b]">Demo teacher profile</p><h1 className="mt-4 font-display text-5xl leading-[0.95] text-[#17324d] sm:text-7xl">{teacher.name}</h1><p className="mt-4 text-xl font-semibold text-[#147d70]">{teacher.specialization}</p><p className="mt-5 max-w-2xl text-lg leading-8 text-[#667085]">{teacher.introduction}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/trial" className={primaryLink}>Book Free Trial <ArrowRight size={17} aria-hidden="true" /></Link><Link href="/teachers" className={outlineLink}>Back to Teachers</Link></div></div></div></section>
    <section className="bg-white py-20"><div className={`${pageWrap} grid gap-14 lg:grid-cols-[1fr_0.8fr]`}><div><PageIntro eyebrow="Teaching approach" title="A supportive relationship with learning." description={teacher.approach} /><div className="mt-10 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#e7e5df] bg-[#fcfbf7] p-6"><Globe2 size={22} className="text-[#147d70]" aria-hidden="true" /><h2 className="mt-5 font-display text-2xl text-[#17324d]">Languages</h2><p className="mt-2 text-sm leading-6 text-[#667085]">{teacher.languages.join(" · ")}</p></div><div className="rounded-2xl border border-[#e7e5df] bg-[#fcfbf7] p-6"><Clock3 size={22} className="text-[#147d70]" aria-hidden="true" /><h2 className="mt-5 font-display text-2xl text-[#17324d]">Availability</h2><p className="mt-2 text-sm leading-6 text-[#667085]">{teacher.availability}</p></div></div></div><div className="rounded-2xl border border-[#e7e5df] bg-[#eef7f3] p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#147d70]">Course expertise</p><ul className="mt-6 space-y-4">{teacher.expertise.map((course) => <li key={course} className="flex gap-3 text-sm font-bold text-[#17324d]"><Check size={18} className="mt-0.5 text-[#147d70]" aria-hidden="true" />{course}</li>)}</ul><div className="mt-8 border-t border-[#d7e9e3] pt-6"><p className="flex gap-3 text-sm leading-6 text-[#667085]"><ShieldCheck size={18} className="mt-1 shrink-0 text-[#147d70]" aria-hidden="true" />Credentials and teacher verification will be provided by the academy service.</p></div></div></div></section>
    <section className="bg-[#fcfbf7] py-20"><div className={`${pageWrap} grid gap-12 lg:grid-cols-[0.8fr_1.2fr]`}><PageIntro eyebrow="Student learning experience" title="The right support can make practice feel lighter." description="Students will be able to connect with their teacher around goals, lesson notes, feedback, and the next small step." /><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#e7e5df] bg-white p-6"><MessageCircle size={22} className="text-[#147d70]" aria-hidden="true" /><h2 className="mt-5 font-display text-2xl text-[#17324d]">Clear feedback</h2><p className="mt-2 text-sm leading-6 text-[#667085]">A future lesson record will keep feedback and next steps together.</p></div><div className="rounded-2xl border border-[#e7e5df] bg-white p-6"><Check size={22} className="text-[#147d70]" aria-hidden="true" /><h2 className="mt-5 font-display text-2xl text-[#17324d]">Steady progress</h2><p className="mt-2 text-sm leading-6 text-[#667085]">Progress indicators will reflect verified learning data, not invented claims.</p></div></div></div></section>
    <section className="bg-white py-20"><div className={`${pageWrap} grid gap-12 lg:grid-cols-[0.8fr_1.2fr]`}><PageIntro eyebrow="Common questions" title="Before you book a trial." /><Accordion items={teacherFaqs} /></div></section>
    <section className="bg-[#147d70] py-20"><div className={`${pageWrap} flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center`}><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#e9ddbf]">Start with a conversation</p><h2 className="mt-2 font-display text-4xl text-white">Find the right learning rhythm.</h2></div><Link href="/trial" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-[#17324d]">Book Free Trial <ArrowRight size={16} aria-hidden="true" /></Link></div></section>
  </main>;
}
